// Schema, dictates how users are saved into mongo
var mongoose = require('mongoose');
var Schema = mongoose.Schema;

var characterSchema = new Schema(
  {
    characterName: String,
    characterClass: String,
    level: String,
    background: String,
    playerName: String,
    race: String,
    alignment: String,
    experience: Number,
    dciNumber: Number,
    strength: Number,
    strengthMod: Number,
    dexterity: Number,
    dexterityMod: Number,
    constitution: Number,
    constitutionMod: Number,
    intelligence: Number,
    intelligenceMod: Number,
    wisdom: Number,
    wisdomMod: Number,
    charisma: Number,
    charismaMod: Number,
    inspiration: Boolean,
    proficiency: Number,
    strengthSaveProficiency: Boolean,
    strengthSave: Number,
    dexteritySaveProficiency: Boolean,
    dexteritySave: Number,
    constitutionSaveProficiency: Boolean,
    constitutionSave: Number,
    intelligenceSaveProficiency: Boolean,
    intelligenceSave: Number,
    wisdomSaveProficiency: Boolean,
    wisdomSave: Number,
    charismaSaveProficiency: Boolean,
    charismaSave: Number,
    acrobaticsProficiency: Boolean,
    acrobatics: Number,
    animalHandlingProficiency: Boolean,
    animalHandling: Number,
    arcanaProficiency: Boolean,
    arcana: Number,
    athleticsProficiency: Boolean,
    athletics: Number,
    deceptionProficiency: Boolean,
    deception: Number,
    historyProficiency: Boolean,
    history: Number,
    insightProficiency: Boolean,
    insight: Number,
    intimidationProficiency: Boolean,
    intimidation: Number,
    investigationProficiency: Boolean,
    investigation: Number,
    medicineProficiency: Boolean,
    medicine: Number,
    natureProficiency: Boolean,
    nature: Number,
    perceptionProficiency: Boolean,
    perception: Number,
    performanceProficiency: Boolean,
    performance: Number,
    persuasionProficiency: Boolean,
    persuasion: Number,
    religionProficiency: Boolean,
    religion: Number,
    slightOfHandProficiency: Boolean,
    slightOfHand: Number,
    stelthProficiency: Boolean,
    stelth: Number,
    survivalProficiency: Boolean,
    survival: Number,
    passivePerception: Number,
    proficiencies: String,
    languages: String,
    armorClass: Number,
    initiative: Number,
    speed: Number,
    hpMax: Number,
    hpCurrent: Number,
    hpTemp: Number,
    hitDieTotal: String,
    hitDie: String,
    deathSave1: Boolean,
    deathSave2: Boolean,
    deathSave3: Boolean,
    deathFail1: Boolean,
    deathFail2: Boolean,
    deathFail3: Boolean,
    attack1: String,
    attackBonus1: Number,
    attackDamage1: String,
    attack2: String,
    attackBonus2: Number,
    attackDamage2: String,
    attack3: String,
    attackBonus3: Number,
    attackDamage3: String,
    attackNotes: String,
    copper: Number,
    silver: Number,
    electrum: Number,
    gold: Number,
    platinum: Number,
    equipment: String,
    personalityTraits: String,
    ideals: String,
    bonds: String,
    flaws: String,
    featuresTraits: String,
    dateCreated: Date,
    lastEdited: Date
  }
);

module.exports = mongoose.model('Character', characterSchema);

/* Cool things you can do with Schemas
{
  username: {type:String, required: true, index: {unique:true}}
  lastlogin: {type: Date, default: Date.now}
}
*/
